-- ============================================================
-- Protocolo do atendimento
-- ============================================================
-- Cada lead ganha um número de protocolo fixo (leads.protocol), usado na
-- variável {{protocolo}} das mensagens agendadas e das automações e
-- mostrado nos dados do lead. Os leads que já existem recebem número na
-- hora; os novos, ao serem criados. Pode rodar mais de uma vez.
-- ============================================================

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'leads' and column_name = 'protocol'
  ) then
    alter table public.leads add column protocol bigint generated by default as identity;
  end if;
end $$;

create unique index if not exists leads_protocol_idx on public.leads (protocol);

notify pgrst, 'reload schema';
